config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  root to: 'games#new'

  resources :games, only: [:create, :show, :new]

  get '/games/share/:id', to: 'games#share'

  post '/newgame', to: 'games#newgame'

  resources :questions, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :artists

  before_validation :set_slug

  validates :init_player_slug, presence: true, uniqueness: true
  validates :guest_player_slug, presence: true, uniqueness: true

  def to_param
    init_player_slug
  end

  private

  def set_slug
    self.init_player_slug = random_string
    self.guest_player_slug = random_string
  end

  def random_string
    SecureRandom.urlsafe_base64(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :newgame
  def show
    @game = Game.find_by(init_player_slug: params[:id]) || Game.find_by(guest_player_slug: params[:id])
    if Game.find_by(init_player_slug: params[:id])
      @starting_player = false
      @player_artist = @game.artists.find_by(spotify_artist_id: @game.init_player_id)
    else
      @starting_player = true
      @player_artist = @game.artists.find_by(spotify_artist_id: @game.guest_player_id)
    end
    @player_slug = params[:id]
    @trivia = ArtistTriviaService.call(@player_artist.name)
  end

  def new
  end

  def create
    @game = GameCreatorService.new.call(params["playlist_uri"])

    if @game.save
      redirect_to "/games/share/#{@game.init_player_slug}"
    else
      render :new
    end
  rescue RestClient::ResourceNotFound
    flash[:alert] = "Cound't find playlist"
    render :new
  end
  
  def newgame
    @game = GameCreatorService.new.call(params["playlist_uri"])

    if @game.save
      render json: @game, status: :ok
    else
      render nothing: true, status: 404
    end
  rescue RestClient::ResourceNotFound
    flash[:alert] = "Cound't find playlist"
    render nothing: true, status: 404
  end

  def share
    @game = Game.find_by(init_player_slug: params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :set_game

  def create
    QuestionsChannel.broadcast_to(@game, broadcast_params)
    render json: params
  end

  private

  def broadcast_params
    {
      msg: params[:msg],
      type: params[:type],
      slug: params[:slug]
    }
  end

  def set_game
    @game = Game.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/new.html.erb
<div id="bg">
  <%= image_tag('crowd_photo.jpg') %>
</div>
<div id="text-wrapper">
  <h1 style="text-transform: uppercase; color: #ff6f64"> Let's play the guessing game! </h1>
  <div>
    Remember the boardgame "Who's there?". This is the same but the persons are artists from your Spotify playlist.
  </div>
  <div>
    <h2> Get started: </h2>
    <ol style="text-align:left">
      <li> Copy the Spotify URI of a playlist into the field at the bottom of this page. Remember that the playlist has to be public in order for the game to work.</li>
      <li> Share the link that will be generated with one of your mates. </li>
      <li> Start asking each other questions to find out who the other person is! Turn away the artists that have been eliminated by clicking at them.</li>
    </ol>
  </div>
  <div class="form">
    <h2>Start a new game:</h2>

    <%= form_tag(action: 'create') do %>
      <%= text_field_tag "playlist_uri" %>
      <%= submit_tag (value = "Start game"), class: "submit-button" %>
    <% end %>
  </div>

<div class="spinner">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>

app/views/games/share.html.erb
<div id="bg">
  <%= image_tag('crowd_photo.jpg') %>
</div>
<div id="text-wrapper">
  <h1>Give this URL to your friend: </h1>

  <p style="color: #00e6de; font-size: 25px"><%= "#{request.base_url}/games/#{@game.guest_player_slug}" %></p>

  <p id="startGameLink"><%= link_to "Now start game!", game_path(@game) %></p>
</div>

app/views/games/show.html.erb
<script>
    window.gameId = <%= @game.id %>;
    window.playerSlug = "<%= @player_slug %>";
    window.startingPlayer = <%= @starting_player %>;
    window.playlist_uri = "<%= @game.playlist_uri %>";

    //MOCK
    window.artistName = "<%= @player_artist.name %>";
    window.artistId = "<%= @player_artist.id %>";
</script>
<div id="top-panel">
    <div id="left-panel">
        <div id="your-artist-box">
            <div id="your-artist-image" style="background-image:url(<%= @player_artist.image_url %>)">
                <div data-preview-url="<%= @player_artist.preview_url %>" class="paused" id="play-btn"></div>
            </div>
            <div id="your-artist-name">
                <p><%= @player_artist.name.upcase %></p>
            </div>
            <div onClick="showTrivia()" class="toggle-trivia">
                Artist info
            </div>
        </div>
        <div id="your-artist-trivia" class="hidden">
            <p><%= @player_artist.name.upcase %></p>
            <p>
                <%= @trivia['bio']['summary'].html_safe %>
            </p>
            <p onClick="hideTrivia()" class="toggle-trivia">
                Back
            </p>
        </div>
    </div>
    <div id="right-panel">
        <div id="right-panel-top">
            <p class="not-your-turn">NOT YOUR TURN</p>
            <p class="your-turn hidden">YOUR TURN</p>
        </div>
        <div id="right-panel-center">
            <p id="question" class="not-your-turn">DOES YOUR ARTIST SING IN ENGLISH?</p>
            <div id="question-input-wrapper" class="your-turn hidden" >
                <input id="question-input" placeholder="Enter a question..."/>
                <div class="btn" onclick="ask()" id="btn-ask">ASK</div>
            </div>
            <p id="asked-question" class="answer hidden"></p>
            <p class="answer hidden">THE ANSWER IS: <span id="answer"></span>!</p>
            <p class="loading hidden">WAITING FOR OTHER PLAYER</p>
            <p class="won hidden">YOU WON!</p>
            <p class="won hidden">Waiting for other player to start a new game.</p>
            <p class="lost hidden">You Lost!</p>
            <p class="lost hidden">Pick a new playlist or play again with the same.</p>
            <div id="new-game-input-wrapper" class="lost hidden" >
                <input id="new-game-input" placeholder="Playlist ID..."/>
                <div class="btn" onclick="newGame(false)" id="btn-new-game">NEW</div>
                <div class="btn" onclick="newGame(true)" id="btn-new-game">SAME</div>
            </div>
        </div>
        <div id="right-panel-bottom">
            <div class="not-your-turn" onclick="answer('yes')" id="btn-answer-yes">YES</div>
            <div class="not-your-turn" onclick="answer('no')" id="btn-answer-no">NO</div>
        </div>
    </div>
</div>
<div id="bottom-panel">
    <% @game.artists.each_with_index do |artist, index| %>
        <div class="flip-container artist-container" onclick="this.classList.toggle('flipped'); toggleBoardMarker(<%=index%>);">
            <div class="artist-marker flipper">
                <div class="front artist-card"><div class="artist-marker-image" style="background-image:url(<%= artist[:image_url] %>)"></div><p><%= artist[:name].upcase %></p></div>
                <div class="back artist-card"><div class="artist-marker-image" style="background-image:url(<%= image_url("record.png")%>)"></div><p><%= artist[:name].upcase %></p></div>
            </div>
        </div>
    <% end %>

</div>
<div id="lie-popup">
    <div id="lie-popup-inner">
        <div id="sad-icon"></div>
        <p>Really? Trying to cheat? Come on!</p>
        <div onClick='$("#lie-popup").hide();'class="btn">SORRY!</div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Guessing Game - Find the artist!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>
    <div id="header">
      <span>The Guessing Game</span>
      <span class="right">
        made at
        <a href="https://github.com/hackoutwest2016/the-guessing-game">Hack Out West 2016</a>
      </span>
    </div>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to this awesome game thing!</h1>